### ISSUE TITLE
Database Not found

### ISSUE THREAD

**Issue by sudhanshuptl** [vishusingh/student-information-system#1]
Database is missing . can u update database

**Comment by emoncse** [comment]
I want too.

**Comment by arksnorman** [comment]
You want to contribute

**Comment by arksnorman** [comment]
@emon-root database is updated

**Comment by emoncse** [comment]
Where will I get it? Can you please give me a link?

**Comment by arksnorman** [comment]
working version of app is here http://arksnorman-sis.herokuapp.com/login/

**Comment by arksnorman** [comment]
use arksnorman as username and 12345 as password

**Comment by arksnorman** [comment]
@emon-root ^

**Comment by bolukom** [comment]
Databse not found

**Comment by arksnorman** [comment]
@bolukom here https://sis.arksnorman.tk/
use admin as username and password
